### ISSUE TITLE
base functions

### ISSUE THREAD

**Issue by 121180875** [RJDennis/SmolyakApprox.jl#10]
This package can draw the base functions?

**Comment by RJDennis** [comment]
The basis functions are Chebyshev polynomials, or "tent" functions if you choose piecewise linear approximation.  The packages doesn't plot them, but the information you need to do so can be extracted from the grid and the interpolation matrix.  The grid is constructed using smolyak_grid() and the inverse interpolation matrix is constructed using smolyak_inverse_interpolation_matrix().  For the 2-D case, you can find these plotted for various layers in numerous papers.
