### ISSUE TITLE
error in smolyak_inverse_interpolation_matrix()

### ISSUE THREAD

**Issue by li-guochen** [RJDennis/SmolyakApprox.jl#11]
I tried to run example.jl but failed due to an error in smolyak_inverse_interpolation_matrix()
I found changing "x::Array{T,1}" to "x::AbstractArray{T,1}" can solve this problem but I don't know if this is an efficient way

![e](https://user-images.githubusercontent.com/55008395/117144559-a65a0c00-ade4-11eb-8935-8ab615714f11.JPG)
![c](https://user-images.githubusercontent.com/55008395/117144556-a528df00-ade4-11eb-8f4b-4d08e2ea7ba3.JPG)

**Comment by RJDennis** [comment]
Thanks. It was some problem related to the use of @views, which I had reverted (unsuccessfully it would appear).  Try it now.

**Comment by li-guochen** [comment]
> Thanks. It was some problem related to the use of @views, which I had reverted (unsuccessfully it would appear). Try it now.

I found @views may improve the speed when handling high dimensional models since it avoids copying large matrices, in order to make it run successfully only need to change the type of the second parameter "x" in chebyshev_polynomial() function from "x::Array{T,1}" to "x::AbstractArray{T,1}", but this change may bring performance penalty. I do not know which one is faster, delete @views or change the parameter type.

**Comment by RJDennis** [comment]
It wasn't giving me performance gains, which is why I reverted it.  Before too long I'll go through all the code for this package again and implement performance improvements.

**Comment by li-guochen** [comment]
> It wasn't giving me performance gains, which is why I reverted it. Before too long I'll go through all the code for this package again and implement performance improvements.

That's great. BTW, I think using CuArray instead of Array when handling high dimensional model may improve performance, such as matrix multiplication, but I also find that CuArray is much slower that Array when using inv() and kron(), so if you have to use kron(), package Kronecker.jl may help you improve the speed.
There is a reference about using CUDA in smolyak method to improve speed (https://github.com/ikarib/smolyak), the speed gain, according to its author, is very attractive. 
I do hope this suggestion may help you since SmolyakApprox helped me a lot.
